// src/screens/onboarding/OnboardingScreen.tsx

import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Animated,
  Dimensions,
  TouchableOpacity,
  ActivityIndicator,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import { useTagStore } from "@stores/tagStore";
import { Tag } from "@type/tag.types";
import TagChip from "@components/tags/TagChip";
import Button from "@components/common/Button";
import Card from "@components/common/Card";
import { COLORS, SPACING, FONT_SIZES, BORDER_RADIUS } from "@constants/colors";
import { mmkvService } from "@services/storage/mmkvService";
import adaptiveRandomizer from "@services/tag-engine/adaptiveRandomizer";

const { width } = Dimensions.get("window");

interface OnboardingScreenProps {
  navigation: any;
}

type SelectionMode = "manual" | "auto";

export const OnboardingScreen: React.FC<OnboardingScreenProps> = ({
  navigation,
}) => {
  const {
    allTags,
    selectedTags: storeSelectedTags,
    selectTag,
    deselectTag,
    loadAllTags,
  } = useTagStore();

  const [selectionMode, setSelectionMode] = useState<SelectionMode>("manual");
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [autoGeneratedTags, setAutoGeneratedTags] = useState<Tag[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const fadeAnim = React.useRef(new Animated.Value(0)).current;
  const slideAnim = React.useRef(new Animated.Value(50)).current;

  useEffect(() => {
    loadAllTags();

    // Entrance animation
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 800,
        useNativeDriver: true,
      }),
      Animated.spring(slideAnim, {
        toValue: 0,
        speed: 12,
        bounciness: 8,
        useNativeDriver: true,
      }),
    ]).start();
  }, []);

  useEffect(() => {
    if (selectionMode === "auto") {
      handleAutoGenerate();
    } else {
      // Clear auto-generated tags when switching to manual
      setAutoGeneratedTags([]);
    }
  }, [selectionMode]);

  const handleAutoGenerate = async () => {
    setIsGenerating(true);
    try {
      // Use adaptive randomizer to select tags
      const generatedTags = await adaptiveRandomizer.selectDailyTags(5);
      setAutoGeneratedTags(generatedTags);

      // Auto-select these tags
      const tagIds = generatedTags.map((tag) => tag.id);
      setSelectedTags(tagIds);

      // Update store
      tagIds.forEach((id) => selectTag(id));
    } catch (error) {
      console.error("[Onboarding] Auto-generate failed:", error);
      // Fallback to manual mode on error
      setSelectionMode("manual");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleTagPress = (tagId: string) => {
    if (selectionMode === "auto") {
      // Don't allow manual changes in auto mode
      return;
    }

    if (selectedTags.includes(tagId)) {
      setSelectedTags(selectedTags.filter((id) => id !== tagId));
      deselectTag(tagId);
    } else {
      if (selectedTags.length < 10) {
        setSelectedTags([...selectedTags, tagId]);
        selectTag(tagId);
      }
    }
  };

  const handleRegenerateAuto = async () => {
    await handleAutoGenerate();
  };

  const handleContinue = async () => {
    if (selectedTags.length >= 5) {
      // Store the selection mode preference
      await mmkvService.set("tag_selection_mode_preference", selectionMode);

      // Mark onboarding as complete
      await mmkvService.set("onboarding_complete", true);

      navigation.replace("Home");
    }
  };

  const groupedTags = allTags.reduce((acc, tag) => {
    const cluster = tag.cluster || "Other";
    if (!acc[cluster]) acc[cluster] = [];
    acc[cluster].push(tag);
    return acc;
  }, {} as Record<string, Tag[]>);

  const getClusterColor = (cluster: string): string => {
    const colors = COLORS.clusters as Record<string, string>;
    return colors[cluster.toLowerCase()] || COLORS.primary.main;
  };

  const progress = (selectedTags.length / 10) * 100;
  const canContinue = selectedTags.length >= 5;

  return (
    <SafeAreaView style={styles.container}>
      <LinearGradient
        colors={["#FFFFFF", "#F0F9FF", "#FEF3F7"]}
        style={styles.gradient}
      >
        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.scrollContent}
        >
          {/* Header */}
          <Animated.View
            style={[
              styles.header,
              {
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }],
              },
            ]}
          >
            <Text style={styles.emoji}>Welcome to{"\n"}Curiosity Engine</Text>
            <Text style={styles.subtitle}>
              Choose how you'd like to select your topics
            </Text>

            {/* Selection Mode Toggle */}
            <Card variant="elevated" style={styles.modeCard}>
              <View style={styles.modeToggleContainer}>
                <TouchableOpacity
                  style={[
                    styles.modeButton,
                    selectionMode === "manual" && styles.modeButtonActive,
                  ]}
                  onPress={() => setSelectionMode("manual")}
                  disabled={isGenerating}
                >
                  <Text
                    style={[
                      styles.modeButtonText,
                      selectionMode === "manual" && styles.modeButtonTextActive,
                    ]}
                  >
                    Manual Selection
                  </Text>
                </TouchableOpacity>

                <TouchableOpacity
                  style={[
                    styles.modeButton,
                    selectionMode === "auto" && styles.modeButtonActive,
                  ]}
                  onPress={() => setSelectionMode("auto")}
                  disabled={isGenerating}
                >
                  <Text
                    style={[
                      styles.modeButtonText,
                      selectionMode === "auto" && styles.modeButtonTextActive,
                    ]}
                  >
                    Auto Generate
                  </Text>
                </TouchableOpacity>
              </View>

              <Text style={styles.modeDescription}>
                {selectionMode === "manual"
                  ? "Select 5-10 topics that interest you"
                  : "Let AI pick topics based on adaptive algorithms"}
              </Text>
            </Card>

            {/* Progress Bar */}
            <View style={styles.progressContainer}>
              <View style={styles.progressBar}>
                <LinearGradient
                  colors={
                    COLORS.gradients.twilight as [string, string, ...string[]]
                  }
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                  style={[styles.progressFill, { width: `${progress}%` }]}
                />
              </View>
              <Text style={styles.progressText}>
                {selectedTags.length}/10 selected
              </Text>
            </View>
          </Animated.View>

          {/* Loading State for Auto Generation */}
          {isGenerating && (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" color={COLORS.primary.main} />
              <Text style={styles.loadingText}>
                Generating personalized tags...
              </Text>
            </View>
          )}

          {/* Auto-Generated Tags Display */}
          {selectionMode === "auto" &&
            !isGenerating &&
            autoGeneratedTags.length > 0 && (
              <Animated.View
                style={{
                  opacity: fadeAnim,
                  transform: [{ translateY: slideAnim }],
                }}
              >
                <Card variant="elevated" style={styles.autoTagsCard}>
                  <Text style={styles.autoTagsTitle}>
                    Your Personalized Topics
                  </Text>
                  <Text style={styles.autoTagsSubtitle}>
                    Selected using adaptive algorithms
                  </Text>

                  <View style={styles.tagsGrid}>
                    {autoGeneratedTags && Array.isArray(autoGeneratedTags) ? autoGeneratedTags.map((tag) => (
                      <TagChip
                        key={tag.id}
                        label={tag.name}
                        selected={true}
                        color={getClusterColor(tag.cluster || "")}
                        variant="gradient"
                        size="medium"
                        style={styles.tag}
                      />
                    )) : null}
                  </View>

                  <Button
                    title="Regenerate Tags"
                    onPress={handleRegenerateAuto}
                    variant="outline"
                    size="medium"
                    fullWidth
                    style={styles.regenerateButton}
                  />
                </Card>
              </Animated.View>
            )}

          {/* Manual Selection - Tags by Cluster */}
          {selectionMode === "manual" && !isGenerating && (
            <Animated.View
              style={{
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }],
              }}
            >
              {groupedTags && typeof groupedTags === 'object' ? Object.entries(groupedTags).map(
                ([cluster, tags], clusterIndex) => (
                  <View key={cluster} style={styles.clusterSection}>
                    {/* Cluster Header */}
                    <View style={styles.clusterHeader}>
                      <View
                        style={[
                          styles.clusterDot,
                          { backgroundColor: getClusterColor(cluster) },
                        ]}
                      />
                      <Text style={styles.clusterName}>{cluster}</Text>
                    </View>

                    {/* Tags */}
                    <View style={styles.tagsGrid}>
                      {tags && Array.isArray(tags) ? tags.map((tag, tagIndex) => {
                        const isSelected = selectedTags.includes(tag.id);

                        return (
                          <TagChip
                            key={tag.id}
                            label={tag.name}
                            selected={isSelected}
                            onPress={() => handleTagPress(tag.id)}
                            color={getClusterColor(cluster)}
                            variant={isSelected ? "gradient" : "outlined"}
                            size="medium"
                            style={styles.tag}
                          />
                        );
                      }) : null}
                    </View>
                  </View>
                )
              ) : null}
            </Animated.View>
          )}

          {/* Bottom Spacing */}
          <View style={{ height: 100 }} />
        </ScrollView>

        {/* Floating Action Button */}
        <Animated.View
          style={[
            styles.floatingButton,
            {
              opacity: fadeAnim,
              transform: [
                {
                  translateY: fadeAnim.interpolate({
                    inputRange: [0, 1],
                    outputRange: [100, 0],
                  }),
                },
              ],
            },
          ]}
        >
          <Button
            title={
              !canContinue
                ? `Select ${5 - selectedTags.length} more`
                : "Let's Start!"
            }
            onPress={handleContinue}
            variant="gradient"
            size="large"
            fullWidth
            disabled={!canContinue || isGenerating}
          />
        </Animated.View>
      </LinearGradient>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.neutral.white,
  },
  gradient: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    alignItems: "center",
    marginBottom: SPACING.xl,
  },
  emoji: {
    fontSize: FONT_SIZES.xxxl,
    fontWeight: "bold",
    color: COLORS.neutral.black,
    textAlign: "center",
    marginBottom: SPACING.sm,
    lineHeight: FONT_SIZES.xxxl * 1.2,
  },
  subtitle: {
    fontSize: FONT_SIZES.md,
    color: COLORS.neutral.gray600,
    textAlign: "center",
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.md,
  },
  modeCard: {
    width: "100%",
    marginBottom: SPACING.lg,
  },
  modeToggleContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.neutral.gray100,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.xs,
    marginBottom: SPACING.md,
  },
  modeButton: {
    flex: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: "center",
  },
  modeButtonActive: {
    backgroundColor: COLORS.primary.main,
  },
  modeButtonText: {
    fontSize: FONT_SIZES.sm,
    fontWeight: "600",
    color: COLORS.neutral.gray600,
  },
  modeButtonTextActive: {
    color: COLORS.neutral.white,
  },
  modeDescription: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.neutral.gray600,
    textAlign: "center",
  },
  progressContainer: {
    width: "100%",
    alignItems: "center",
  },
  progressBar: {
    width: "100%",
    height: 8,
    backgroundColor: COLORS.neutral.gray200,
    borderRadius: BORDER_RADIUS.full,
    overflow: "hidden",
    marginBottom: SPACING.sm,
  },
  progressFill: {
    height: "100%",
    borderRadius: BORDER_RADIUS.full,
  },
  progressText: {
    fontSize: FONT_SIZES.sm,
    fontWeight: "600",
    color: COLORS.primary.main,
  },
  loadingContainer: {
    alignItems: "center",
    paddingVertical: SPACING.xxxl,
  },
  loadingText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.neutral.gray600,
    marginTop: SPACING.md,
  },
  autoTagsCard: {
    marginBottom: SPACING.xl,
  },
  autoTagsTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: "bold",
    color: COLORS.neutral.black,
    marginBottom: SPACING.xs,
    textAlign: "center",
  },
  autoTagsSubtitle: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.neutral.gray600,
    marginBottom: SPACING.lg,
    textAlign: "center",
  },
  regenerateButton: {
    marginTop: SPACING.md,
  },
  clusterSection: {
    marginBottom: SPACING.xl,
  },
  clusterHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  clusterDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: SPACING.sm,
  },
  clusterName: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "700",
    color: COLORS.neutral.black,
    textTransform: "capitalize",
  },
  tagsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -SPACING.xs,
  },
  tag: {
    margin: SPACING.xs,
  },
  floatingButton: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.neutral.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.neutral.gray200,
  },
});

export default OnboardingScreen;
